const Portfolio_data = [
    {
      id: 1,
      category: "Dapp Reactjs site",
      totalLike: "600",
      title: "This website for integrate with Blockchain contract using React js,Web3.js ",
      image: "./imgprojects/im1.png",
      src: "https://mirasociety.com/",
    },
    {
      id: 2,
      category: "Front-end Site React JS",
      totalLike: "750",
      title: "My website was made by React Js and styled-component",
      image: "./imgprojects/im5.png",
      src: "https://mirasociety.com/",
    },
    {
      id: 3,
      category: "Front-end Site React JS",
      totalLike: "630",
      title: "My website was made by React Js and styled-component with animation js",
      image: "./imgprojects/im3.png",
      src: "https://mirasociety.com/",
    },
    {
      id: 4,
      category: "Front-end Site React JS",
      totalLike: "360",
      title: "My website was made by React Js and styled-component",
      image: "./imgprojects/im2.jpg",
      src: "https://mirasociety.com/",
    },
    {
      id: 5,
      category: "UI/UX WEB DESIGN",
      totalLike: "280",
      title: "Designe web page ui-ux by using XD",
      image: "./imgprojects/im4.png",
      src: "https://mirasociety.com/",
    },
    {
      id: 6,
      category: "UI/UX Mobile Application",
      totalLike: "690",
      title: "Designe App screens ui-ux by using XD",
      image: "./imgprojects/im6.png",
      src: "https://mirasociety.com/",
    },
  ]
  export default Portfolio_data